### PR TITLE
[#486] Get all admin level accounts

### LINKED ISSUE #486: Get all admin level accounts
The current `/admin/application/accounts` API only retrieves accounts having a provided `account-id` or `auth-type-identifier`. We should add additional parameters to the request to allow Admin App users to retrieve lists of accounts with admin-level permissions, roles, or groups for each app/org they have access to. This will make managing admin-level accounts easier.

### PR DESCRIPTION
**Pull request by roberlander2**
## Description
This PR adds more search parameters and pagination parameters to the GET `/admin/application/accounts` API. It also adds this updated API to the `services` subrouter.

Depends on #487 and #508.

**Resolves #486**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires updating the documentation.
- [x] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Review by shurwit — COMMENTED** [review]
Thanks @roberlander2, LGTM! Just one minor comment below

**Comment by shurwit** [comment]
As discussed, we may want to reintroduce an `admin` flag in the accounts to avoid inefficient queries involving permissions, roles, and groups currently needed. This should be set/removed when creating/updating accounts based on the existence of permissions/roles/groups.

**Comment by roberlander2** [comment]
The account `admin` flag will require additional management due to changes introduced by #487 and #508.

**Review by shurwit — APPROVED** [review]
Thanks @roberlander2, LGTM!

**Pull request merged**
