### PR TITLE
[#589] Update profile when external user info changes

### LINKED ISSUE #535: [BUG] Fix external system role/group synchronization
**Describe the bug**

Currently when roles/groups are set by an external system, we check for changes against the previous roles/groups in that system to determine whether to add/remove roles/groups from the account. This will mean that it will be possible for the account roles/groups to be unintentionally desynchronized from the roles/groups in the external system.

**To Reproduce**
1. Login with external auth type that contains roles that are not yet defined in the Core BB
2. Define the role in the Core BB
3. Login again
4. See that account still does not have external roles

**Expected behavior**

We should compare the external roles/groups to the account roles/groups on login to ensure that the account roles/groups always stay in sync. Only the `admin_set` flag should override this mechanism.

### LINKED ISSUE #546: [BUG] External ID synchronization
**Describe the bug**

Currently when external IDs are set by an external system, we check for changes against the previous external IDs in that system to determine whether to add/remove external IDs from the account. This will mean that it will be possible for the account external IDs to be unintentionally desynchronized from the external IDs in the external system.

**To Reproduce**
1. Login with external auth type that contains external IDs
2. Manually change external ID
3. Login again
4. See that account still has manually set external ID

**Expected behavior**

We should compare the external system external IDs to the account external IDs on login to ensure that the account external IDs always stay in sync.

### LINKED ISSUE #589: [BUG] Update profile when external user info changes
**Describe the bug**
Currently if user info changes in an external system the account profile is not updated if those fields are set.

**To Reproduce**
1. Change user info in external system
2. Login using external auth type
3. See profile is not updated

**Expected behavior**
If the user info in an external system changes from the previous value that came from that system the profile should be updated with the latest value. This will ensure that changes from external systems are reflected and that data set by the user is not overwritten constantly.

### PR DESCRIPTION
**Pull request by shurwit**
## Description
_Please provide a summary of the pull request and the issue it resolves. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Resolves #589 Resolves #535 Resolves #546** 

**Depends on: #592**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Review by roberlander2 — COMMENTED** [review]
Thanks @shurwit I think this all looks good. One question:
Should linking an external auth type update the profile like login and refresh do? Right now, it does not.

**Review by petyos — DISMISSED** [review]
It looks good to me.

**Comment by shurwit** [comment]
> Thanks @shurwit I think this all looks good. One question: Should linking an external auth type update the profile like login and refresh do? Right now, it does not.

I think we do not need to worry about that since the user will need to login with the external auth type before using it anyway.

**Comment by shurwit** [comment]
We still need to address the existing de-synchronized accounts. To deal with this, we should add one or more flags to the identity provider settings that determine if the profile (and other account data) is always updated to match the external user regardless of its current state. When doing this, we should avoid making DB calls unless we know that something was actually updated.

**Review by shurwit — COMMENTED** [review]
Thanks @roberlander2, LGTM! @petyos, please take another look at this when you get a chance. Thanks!

**Review by petyos — APPROVED** [review]
It looks good to me.

**Pull request merged**
