### PR TITLE
[#559] Anonymous accounts

### LINKED ISSUE #559: [FEATURE] Anonymous accounts
**Is your feature request related to a problem? Please describe.**

In some cases we may want to store data on anonymous users in the back-end of the system. At the moment, anonymous users do not receive an account record at all, so there is no place to store this data.

**Describe the solution you'd like**

We should allow accounts to be created for anonymous users that contain only non-personally identifiable information (preferences, system configs (#558), dates...). These accounts should have an `anonymous` flag set on them to differentiate them from normal accounts. These accounts **MUST NOT** contain any PII or permissions. Any APIs that set this type of data must be restricted from accessing anonymous accounts.

We will likely also want to periodically clear any of these accounts that are unused for some period of time since anonymous IDs can easily be lost or reset, which could leave many dead records.

**Describe alternatives you've considered**

An alternative would be to store this data outside of the account collection, however this would likely cause more confusion and complications in the future since the functionality will be similar to that of accounts. We will just need to be careful to account for the existence of anonymous accounts when processing account records.

### PR DESCRIPTION
**Pull request by shurwit**
## Description
_Please provide a summary of the pull request and the issue it resolves. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Resolves #559**

Depends on #560 

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires updating the documentation.
- [x] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by petyos** [comment]
Hi @shurwit ,

Do we have any issues with the current anonymous implementation not creating anonymous account or this is just an improvement?
Thanks.

**Comment by shurwit** [comment]
Hi @petyos, this was just an improvement intended to allow us to use the system configs defined in #558 for anonymous users. We decided to put off handling anonymous users to make sure that this change doesn't have any unintended consequences. This is a significant change and we will have to be careful to handle these anonymous account records correctly whenever retrieving account data, so there is no rush to merge this. I do however think that this would be a useful feature to support in the platform once we have verified that it won't cause any issues.

**Review by petyos — APPROVED** [review]
Hi @shurwit , all this looks good to me.

**Comment by petyos** [comment]
Hi @shurwit , @roberlander2 , is there anything you think to cover in this issue or it is ready to be merged?

**Pull request merged**
